name: Terraform Deployment
on: push
jobs:
  deploy:
    env:
      AZURE_SECRET_ACCESS_KEY: "${{ secrest.AZURE_SECRET_ACCESS_KEY }}"
    runs-on: Canonical-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
          
